version: "3.8"

services:
  thrico-web:
    container_name: thrico-web
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile-web
    # assuming your app runs on port 3000 inside the container
    environment:
      - NODE_ENV=production
    networks:
      - web

networks:
  web:
    driver: bridge
