version: "3.8"

services:
  thrico-web:
    container_name: thrico-web
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile-web
    ports:
      - "4000:4000" # Exposing port 4000 internally to 80 externally
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`*.thrico.community`)"
      - "traefik.http.services.app.loadbalancer.server.port=80" # The port your app is listening on
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    networks:
      - webnet

  # Other services (e.g., login, backend) can be added similarly

networks:
  webnet:
    driver: bridge
